// Generated by ScriptBuilder - 306 – Validation Middleware
// Feature: validation | Role: middleware

// =========================================================
// 007 – Validation Middleware
// Feature: validation
// Role: middleware
// Group: Middleware
// =========================================================
// FILE: src/middleware/validate.js
// =========================================================

const { validationResult, body, param, query } = require('express-validator');

// Run validation and return errors
const validate = (req, res, next) => {
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).json({ 
      error: 'Validation failed',
      details: errors.array().map(e => ({
        field: e.path,
        message: e.msg,
      })),
    });
  }
  next();
};

// User registration rules
const registerRules = [
  body('email').isEmail().normalizeEmail().withMessage('Valid email required'),
  body('phone').isMobilePhone().withMessage('Valid phone number required'),
  body('password').isLength({ min: 8 }).withMessage('Password must be at least 8 characters'),
  body('name').trim().isLength({ min: 2, max: 100 }).withMessage('Name required (2-100 chars)'),
  body('userType').isIn(['shipper', 'driver']).withMessage('User type must be shipper or driver'),
];

// Login rules
const loginRules = [
  body('email').isEmail().normalizeEmail().withMessage('Valid email required'),
  body('password').notEmpty().withMessage('Password required'),
];

// Load creation rules
const createLoadRules = [
  body('weightLbs').isInt({ min: 1, max: 80000 }).withMessage('Weight required (1-80000 lbs)'),
  body('lengthIn').optional().isInt({ min: 1 }).withMessage('Length must be positive'),
  body('widthIn').optional().isInt({ min: 1 }).withMessage('Width must be positive'),
  body('heightIn').optional().isInt({ min: 1 }).withMessage('Height must be positive'),
  body('palletCount').optional().isInt({ min: 1, max: 52 }).withMessage('Pallet count (1-52)'),
  
  body('pickupAddress').trim().notEmpty().withMessage('Pickup address required'),
  body('pickupCity').trim().notEmpty().withMessage('Pickup city required'),
  body('pickupState').isLength({ min: 2, max: 2 }).withMessage('Pickup state (2 letter code)'),
  
  body('deliveryAddress').trim().notEmpty().withMessage('Delivery address required'),
  body('deliveryCity').trim().notEmpty().withMessage('Delivery city required'),
  body('deliveryState').isLength({ min: 2, max: 2 }).withMessage('Delivery state (2 letter code)'),
];

// Driver profile rules
const driverProfileRules = [
  body('cdlNumber').trim().notEmpty().withMessage('CDL number required'),
  body('cdlState').isLength({ min: 2, max: 2 }).withMessage('CDL state (2 letter code)'),
  body('cdlExpiry').isISO8601().withMessage('Valid CDL expiry date required'),
  body('truckType').optional().trim(),
  body('maxWeightLbs').optional().isInt({ min: 1000 }).withMessage('Max weight must be at least 1000 lbs'),
];

// Location update rules
const locationRules = [
  body('latitude').isFloat({ min: -90, max: 90 }).withMessage('Valid latitude required'),
  body('longitude').isFloat({ min: -180, max: 180 }).withMessage('Valid longitude required'),
  body('heading').optional().isFloat({ min: 0, max: 360 }),
  body('speedMph').optional().isFloat({ min: 0 }),
];

// UUID param validation
const uuidParam = (paramName) => [
  param(paramName).isUUID().withMessage(`Valid ${paramName} required`),
];

module.exports = {
  validate,
  registerRules,
  loginRules,
  createLoadRules,
  driverProfileRules,
  locationRules,
  uuidParam,
};
