// Generated by ScriptBuilder - 322 – Document Routes
// Feature: core | Role: core

// =========================================================
// 322 – Document Routes
// Feature: documents
// Role: routes
// Group: Backend API
// =========================================================
// FILE: src/routes/documents.js
// =========================================================

const express = require('express');
const router = express.Router();
const { pool } = require('../db/pool');
const { authenticate, requireUserType } = require('../middleware/auth');
const documentService = require('../services/documentService');

// Get upload URL (driver requests presigned URL, then uploads directly to S3)
router.post('/upload-url', authenticate, requireUserType('driver'), async (req, res) => {
  try {
    const { documentType, contentType, fileName } = req.body;
    
    if (!documentType || !contentType || !fileName) {
      return res.status(400).json({ error: 'Missing required fields' });
    }
    
    const result = await documentService.getUploadUrl(
      req.user.id,
      documentType,
      contentType,
      fileName
    );
    
    res.json(result);
  } catch (error) {
    console.error('[Documents] Upload URL error:', error);
    res.status(400).json({ error: error.message });
  }
});

// Confirm upload (after client uploads to S3)
router.post('/confirm-upload', authenticate, requireUserType('driver'), async (req, res) => {
  try {
    const { documentType, s3Key } = req.body;
    
    if (!documentType || !s3Key) {
      return res.status(400).json({ error: 'Missing required fields' });
    }
    
    // Store document reference in database
    await pool.query(`
      INSERT INTO driver_documents (user_id, document_type, s3_key, status, uploaded_at)
      VALUES ($1, $2, $3, 'pending', NOW())
      ON CONFLICT (user_id, document_type)
      DO UPDATE SET s3_key = $3, status = 'pending', uploaded_at = NOW()
    `, [req.user.id, documentType, s3Key]);
    
    // Check if all required documents are uploaded
    const status = await documentService.getDriverDocumentStatus(pool, req.user.id);
    
    // If all docs uploaded, update profile status
    if (status.complete) {
      await pool.query(`
        UPDATE driver_profiles 
        SET verification_status = 'documents_submitted', updated_at = NOW()
        WHERE user_id = $1 AND verification_status IN ('pending', 'documents_required')
      `, [req.user.id]);
    }
    
    res.json({ 
      success: true, 
      documentStatus: status 
    });
  } catch (error) {
    console.error('[Documents] Confirm upload error:', error);
    res.status(500).json({ error: 'Failed to confirm upload' });
  }
});

// Get document status
router.get('/status', authenticate, requireUserType('driver'), async (req, res) => {
  try {
    const status = await documentService.getDriverDocumentStatus(pool, req.user.id);
    res.json(status);
  } catch (error) {
    console.error('[Documents] Status error:', error);
    res.status(500).json({ error: 'Failed to get document status' });
  }
});

// Get view URL for a document
router.get('/view/:documentType', authenticate, async (req, res) => {
  try {
    const { documentType } = req.params;
    
    // Get S3 key from database
    const result = await pool.query(
      `SELECT s3_key FROM driver_documents
       WHERE user_id = $1 AND document_type = $2`,
      [req.user.id, documentType]
    );
    
    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Document not found' });
    }
    
    const viewUrl = await documentService.getViewUrl(result.rows[0].s3_key);
    res.json({ url: viewUrl, expiresIn: 3600 });
  } catch (error) {
    console.error('[Documents] View error:', error);
    res.status(500).json({ error: 'Failed to get document URL' });
  }
});

// Delete document
router.delete('/:documentType', authenticate, requireUserType('driver'), async (req, res) => {
  try {
    const { documentType } = req.params;
    
    // Get S3 key
    const result = await pool.query(
      `SELECT s3_key FROM driver_documents
       WHERE user_id = $1 AND document_type = $2`,
      [req.user.id, documentType]
    );
    
    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Document not found' });
    }
    
    // Delete from S3
    await documentService.deleteFile(result.rows[0].s3_key);
    
    // Delete from database
    await pool.query(
      `DELETE FROM driver_documents WHERE user_id = $1 AND document_type = $2`,
      [req.user.id, documentType]
    );
    
    // Update verification status if needed
    await pool.query(`
      UPDATE driver_profiles 
      SET verification_status = 'documents_required', updated_at = NOW()
      WHERE user_id = $1 AND verification_status = 'documents_submitted'
    `, [req.user.id]);
    
    res.json({ success: true });
  } catch (error) {
    console.error('[Documents] Delete error:', error);
    res.status(500).json({ error: 'Failed to delete document' });
  }
});

// Upload proof of delivery for a load
router.post('/pod/:loadId', authenticate, requireUserType('driver'), async (req, res) => {
  try {
    const { loadId } = req.params;
    const { contentType, fileName } = req.body;
    
    // Verify driver owns this load
    const loadResult = await pool.query(
      `SELECT id FROM loads WHERE id = $1 AND driver_id = $2`,
      [loadId, req.user.id]
    );
    
    if (loadResult.rows.length === 0) {
      return res.status(403).json({ error: 'Not authorized for this load' });
    }
    
    const result = await documentService.getUploadUrl(
      loadId,
      'proof_of_delivery',
      contentType,
      fileName
    );
    
    res.json(result);
  } catch (error) {
    console.error('[Documents] POD upload error:', error);
    res.status(500).json({ error: 'Failed to get upload URL' });
  }
});

module.exports = router;
