// Generated by ScriptBuilder - 325 – Verification Routes
// Feature: core | Role: core

// =========================================================
// 325 – Verification Routes
// Feature: verification
// Role: routes
// Group: Backend API
// =========================================================
// FILE: src/routes/verification.js
// =========================================================

const express = require('express');
const router = express.Router();
const { pool } = require('../db/pool');
const { authenticate, requireUserType } = require('../middleware/auth');
const verificationService = require('../services/verificationService');

// Get verification status
router.get('/status', authenticate, requireUserType('driver'), async (req, res) => {
  try {
    const status = await verificationService.getVerificationStatus(req.user.id);
    res.json(status);
  } catch (error) {
    console.error('[Verification] Status error:', error);
    res.status(500).json({ error: 'Failed to get verification status' });
  }
});

// Submit for verification (after documents uploaded)
router.post('/submit', authenticate, requireUserType('driver'), async (req, res) => {
  try {
    const { dateOfBirth, ssnLast4, firstName, lastName } = req.body;
    
    // Validate required fields
    if (!dateOfBirth || !ssnLast4 || !firstName || !lastName) {
      return res.status(400).json({ error: 'Missing required fields' });
    }
    
    // Get driver profile
    const profileResult = await pool.query(
      `SELECT * FROM driver_profiles WHERE user_id = $1`,
      [req.user.id]
    );
    
    if (profileResult.rows.length === 0) {
      return res.status(400).json({ error: 'Driver profile not found' });
    }
    
    const profile = profileResult.rows[0];
    
    // Check documents are complete
    const docStatus = await pool.query(
      `SELECT document_type FROM driver_documents 
       WHERE driver_id = $1 AND status != 'rejected'`,
      [req.user.id]
    );
    
    const uploadedTypes = docStatus.rows.map(d => d.document_type);
    const requiredDocs = ['cdl_front', 'cdl_back', 'insurance_certificate'];
    const missingDocs = requiredDocs.filter(d => !uploadedTypes.includes(d));
    
    if (missingDocs.length > 0) {
      return res.status(400).json({ 
        error: 'Missing required documents',
        missing: missingDocs,
      });
    }
    
    // Get user info
    const userResult = await pool.query(
      `SELECT email, phone FROM users WHERE id = $1`,
      [req.user.id]
    );
    
    // Create Checkr candidate
    const candidateResult = await verificationService.createCandidate(req.user.id, {
      firstName,
      lastName,
      email: userResult.rows[0].email,
      phone: userResult.rows[0].phone,
      dateOfBirth, // YYYY-MM-DD
      ssn: ssnLast4,
      cdlNumber: profile.cdl_number,
      cdlState: profile.cdl_state,
    });
    
    if (!candidateResult.success) {
      return res.status(400).json({ error: candidateResult.error });
    }
    
    // Create background check invitation
    const invitationResult = await verificationService.createInvitation(
      candidateResult.candidateId,
      'driver_pro'
    );
    
    if (!invitationResult.success) {
      return res.status(400).json({ error: invitationResult.error });
    }
    
    // Update status
    await pool.query(
      `UPDATE driver_profiles 
       SET verification_status = 'background_check_pending', updated_at = NOW()
       WHERE user_id = $1`,
      [req.user.id]
    );
    
    res.json({
      message: 'Background check initiated',
      invitationUrl: invitationResult.invitationUrl,
      status: 'background_check_pending',
    });
  } catch (error) {
    console.error('[Verification] Submit error:', error);
    res.status(500).json({ error: 'Failed to submit for verification' });
  }
});

// Update driver profile info
router.patch('/profile', authenticate, requireUserType('driver'), async (req, res) => {
  try {
    const { 
      cdlNumber, cdlState, cdlExpiry,
      mcNumber, dotNumber,
      insuranceProvider, insurancePolicyNumber, insuranceExpiry,
      truckType, maxWeightLbs, trailerLengthFt
    } = req.body;
    
    const updates = [];
    const params = [req.user.id];
    let paramIndex = 2;
    
    if (cdlNumber) { updates.push(`cdl_number = $${paramIndex++}`); params.push(cdlNumber); }
    if (cdlState) { updates.push(`cdl_state = $${paramIndex++}`); params.push(cdlState); }
    if (cdlExpiry) { updates.push(`cdl_expiry = $${paramIndex++}`); params.push(cdlExpiry); }
    if (mcNumber) { updates.push(`mc_number = $${paramIndex++}`); params.push(mcNumber); }
    if (dotNumber) { updates.push(`dot_number = $${paramIndex++}`); params.push(dotNumber); }
    if (insuranceProvider) { updates.push(`insurance_provider = $${paramIndex++}`); params.push(insuranceProvider); }
    if (insurancePolicyNumber) { updates.push(`insurance_policy_number = $${paramIndex++}`); params.push(insurancePolicyNumber); }
    if (insuranceExpiry) { updates.push(`insurance_expiry = $${paramIndex++}`); params.push(insuranceExpiry); }
    if (truckType) { updates.push(`truck_type = $${paramIndex++}`); params.push(truckType); }
    if (maxWeightLbs) { updates.push(`max_weight_lbs = $${paramIndex++}`); params.push(maxWeightLbs); }
    if (trailerLengthFt) { updates.push(`trailer_length_ft = $${paramIndex++}`); params.push(trailerLengthFt); }
    
    if (updates.length === 0) {
      return res.status(400).json({ error: 'No updates provided' });
    }
    
    updates.push('updated_at = NOW()');
    
    await pool.query(
      `UPDATE driver_profiles SET ${updates.join(', ')} WHERE user_id = $1`,
      params
    );
    
    res.json({ message: 'Profile updated' });
  } catch (error) {
    console.error('[Verification] Profile update error:', error);
    res.status(500).json({ error: 'Failed to update profile' });
  }
});

// Checkr webhook endpoint
router.post('/webhook/checkr', express.raw({ type: 'application/json' }), async (req, res) => {
  try {
    // Verify webhook signature (in production)
    // const signature = req.headers['x-checkr-signature'];
    
    const event = JSON.parse(req.body);
    await verificationService.handleCheckrWebhook(event);
    
    res.status(200).send('OK');
  } catch (error) {
    console.error('[Verification] Webhook error:', error);
    res.status(500).send('Error');
  }
});

module.exports = router;
