// Generated by ScriptBuilder - 321 – Analytics Service
// Feature: core | Role: core

// =========================================================
// 321 – Analytics Service
// Feature: analytics
// Role: tracking
// Group: Backend API
// =========================================================
// FILE: src/services/analyticsService.js
// =========================================================

const Mixpanel = require('mixpanel');
const config = require('../config');

// Initialize Mixpanel
const mixpanel = config.mixpanel.token 
  ? Mixpanel.init(config.mixpanel.token, { host: 'api.mixpanel.com' })
  : null;

// Event names
const EVENTS = {
  // User events
  USER_SIGNED_UP: 'User Signed Up',
  USER_LOGGED_IN: 'User Logged In',
  USER_LOGGED_OUT: 'User Logged Out',
  PROFILE_UPDATED: 'Profile Updated',
  
  // Driver events
  DRIVER_WENT_ONLINE: 'Driver Went Online',
  DRIVER_WENT_OFFLINE: 'Driver Went Offline',
  DRIVER_LOCATION_UPDATED: 'Driver Location Updated',
  DRIVER_VERIFIED: 'Driver Verified',
  DOCUMENTS_UPLOADED: 'Documents Uploaded',
  
  // Load events
  LOAD_CREATED: 'Load Created',
  LOAD_POSTED: 'Load Posted',
  LOAD_VIEWED: 'Load Viewed',
  LOAD_ACCEPTED: 'Load Accepted',
  LOAD_PICKED_UP: 'Load Picked Up',
  LOAD_DELIVERED: 'Load Delivered',
  LOAD_CANCELLED: 'Load Cancelled',
  
  // Payment events
  PAYMENT_INITIATED: 'Payment Initiated',
  PAYMENT_COMPLETED: 'Payment Completed',
  PAYMENT_FAILED: 'Payment Failed',
  PAYOUT_SENT: 'Payout Sent',
  
  // Dispute events
  DISPUTE_OPENED: 'Dispute Opened',
  DISPUTE_RESOLVED: 'Dispute Resolved',
  
  // Search events
  LOADS_SEARCHED: 'Loads Searched',
  DRIVERS_SEARCHED: 'Drivers Searched',
};

// Track event
const track = (userId, event, properties = {}) => {
  if (!mixpanel) {
    console.log(`[Analytics] (disabled) ${event}`, { userId, ...properties });
    return;
  }
  
  try {
    mixpanel.track(event, {
      distinct_id: userId,
      time: Date.now(),
      ...properties,
    });
  } catch (error) {
    console.error('[Analytics] Track failed:', error.message);
  }
};

// Set user profile
const setUserProfile = (userId, properties) => {
  if (!mixpanel) return;
  
  try {
    mixpanel.people.set(userId, {
      ...properties,
      $last_seen: new Date().toISOString(),
    });
  } catch (error) {
    console.error('[Analytics] Set profile failed:', error.message);
  }
};

// Increment user property
const increment = (userId, property, amount = 1) => {
  if (!mixpanel) return;
  
  try {
    mixpanel.people.increment(userId, property, amount);
  } catch (error) {
    console.error('[Analytics] Increment failed:', error.message);
  }
};

// Track revenue
const trackRevenue = (userId, amount, properties = {}) => {
  if (!mixpanel) return;
  
  try {
    mixpanel.people.track_charge(userId, amount, {
      time: new Date().toISOString(),
      ...properties,
    });
  } catch (error) {
    console.error('[Analytics] Track revenue failed:', error.message);
  }
};

// ─────────────────────────────────────────────────────────────
// Specific tracking functions
// ─────────────────────────────────────────────────────────────

const trackSignUp = (userId, userType, source = 'organic') => {
  track(userId, EVENTS.USER_SIGNED_UP, { user_type: userType, source });
  setUserProfile(userId, {
    $created: new Date().toISOString(),
    user_type: userType,
    signup_source: source,
  });
};

const trackLogin = (userId, method = 'email') => {
  track(userId, EVENTS.USER_LOGGED_IN, { method });
  setUserProfile(userId, { $last_login: new Date().toISOString() });
};

const trackLoadCreated = (userId, loadDetails) => {
  track(userId, EVENTS.LOAD_CREATED, {
    load_id: loadDetails.id,
    weight_lbs: loadDetails.weightLbs,
    distance_miles: loadDetails.distanceMiles,
    price_cents: loadDetails.priceCents,
    pickup_state: loadDetails.pickupState,
    delivery_state: loadDetails.deliveryState,
  });
  increment(userId, 'loads_created');
};

const trackLoadAccepted = (driverId, loadDetails) => {
  track(driverId, EVENTS.LOAD_ACCEPTED, {
    load_id: loadDetails.id,
    shipper_id: loadDetails.shipperId,
    price_cents: loadDetails.priceCents,
    distance_miles: loadDetails.distanceMiles,
  });
  increment(driverId, 'loads_accepted');
};

const trackLoadDelivered = (driverId, loadDetails) => {
  track(driverId, EVENTS.LOAD_DELIVERED, {
    load_id: loadDetails.id,
    payout_cents: loadDetails.driverPayoutCents,
    delivery_time_minutes: loadDetails.deliveryTimeMinutes,
  });
  increment(driverId, 'loads_delivered');
  trackRevenue(driverId, loadDetails.driverPayoutCents / 100, {
    load_id: loadDetails.id,
  });
};

const trackPaymentCompleted = (shipperId, paymentDetails) => {
  track(shipperId, EVENTS.PAYMENT_COMPLETED, {
    load_id: paymentDetails.loadId,
    amount_cents: paymentDetails.amountCents,
    payment_method: paymentDetails.method,
  });
  increment(shipperId, 'total_spent', paymentDetails.amountCents);
};

const trackDriverOnline = (driverId, location) => {
  track(driverId, EVENTS.DRIVER_WENT_ONLINE, {
    city: location.city,
    state: location.state,
  });
  setUserProfile(driverId, { 
    is_online: true,
    last_online_city: location.city,
  });
};

const trackDriverOffline = (driverId, onlineDurationMinutes) => {
  track(driverId, EVENTS.DRIVER_WENT_OFFLINE, {
    online_duration_minutes: onlineDurationMinutes,
  });
  setUserProfile(driverId, { is_online: false });
  increment(driverId, 'total_online_minutes', onlineDurationMinutes);
};

module.exports = {
  EVENTS,
  track,
  setUserProfile,
  increment,
  trackRevenue,
  // Specific trackers
  trackSignUp,
  trackLogin,
  trackLoadCreated,
  trackLoadAccepted,
  trackLoadDelivered,
  trackPaymentCompleted,
  trackDriverOnline,
  trackDriverOffline,
};
