// Generated by ScriptBuilder - 319 – Email Service (SendGrid)
// Feature: core | Role: core

// =========================================================
// 319 – Email Service (SendGrid)
// Feature: notifications
// Role: email
// Group: Backend API
// =========================================================
// FILE: src/services/emailService.js
// =========================================================

const sgMail = require('@sendgrid/mail');
const config = require('../config');
