// Generated by ScriptBuilder - 308 – Geocoding Service
// Feature: geo | Role: service

// =========================================================
// 009 – Geocoding Service
// Feature: geo
// Role: service
// Group: Services
// =========================================================
// FILE: src/services/geocoding.js
// =========================================================

const config = require('../config');

/**
 * Geocode an address to lat/lon coordinates
 * Uses Google Maps Geocoding API
 * 
 * TODO: Add actual Google Maps API key and implementation
 * For now, returns mock data for testing
 */
const geocodeAddress = async (address, city, state, zip = '') => {
  const fullAddress = `${address}, ${city}, ${state} ${zip}`.trim();
  
  // TODO: Replace with actual Google Maps API call
  // const response = await fetch(
  //   `https://maps.googleapis.com/maps/api/geocode/json?address=${encodeURIComponent(fullAddress)}&key=${config.google.apiKey}`
  // );
  
  // Mock response for testing
  console.log(`[Geocoding] Would geocode: ${fullAddress}`);
  
  // Return mock coordinates (Memphis, TN area)
  return {
    latitude: 35.1495 + (Math.random() * 0.1 - 0.05),
    longitude: -90.0490 + (Math.random() * 0.1 - 0.05),
    formattedAddress: fullAddress,
  };
};

/**
 * Calculate distance between two coordinates (Haversine formula)
 */
const calculateDistance = (lat1, lon1, lat2, lon2) => {
  const R = 3959; // Earth's radius in miles
  const dLat = toRad(lat2 - lat1);
  const dLon = toRad(lon2 - lon1);
  
  const a = 
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) *
    Math.sin(dLon / 2) * Math.sin(dLon / 2);
  
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  const distance = R * c;
  
  return Math.round(distance * 100) / 100;
};

const toRad = (deg) => deg * (Math.PI / 180);

/**
 * Estimate drive time based on distance
 * Assumes average speed of 55 mph for trucking
 */
const estimateDriveTime = (distanceMiles, avgSpeedMph = 55) => {
  const hours = distanceMiles / avgSpeedMph;
  const minutes = Math.round(hours * 60);
  return minutes;
};

module.exports = {
  geocodeAddress,
  calculateDistance,
  estimateDriveTime,
};
