// Generated by ScriptBuilder - 307 – Pricing Service
// Feature: pricing | Role: service

// =========================================================
// 008 – Pricing Service
// Feature: pricing
// Role: service
// Group: Services
// =========================================================
// FILE: src/services/pricing.js
// =========================================================

const config = require('../config');

/**
 * Calculate load price based on distance, weight, and config
 * 
 * Formula:
 *   basePrice = baseFee + (distance * perMileRate) + (overweightLbs * perPoundRate)
 *   fuelSurcharge = basePrice * fuelSurchargePercent
 *   platformFee = (basePrice + fuelSurcharge) * platformFeePercent
 *   totalPrice = basePrice + fuelSurcharge + platformFee
 *   driverPayout = totalPrice - platformFee
 */
const calculatePrice = (distanceMiles, weightLbs, options = {}) => {
  const {
    baseFee = config.pricing.baseFee,
    perMileRate = config.pricing.perMileRate,
    perPoundRate = config.pricing.perPoundRate,
    fuelSurchargePercent = config.pricing.fuelSurchargePercent,
    platformFeePercent = config.pricing.platformFeePercent,
    minPrice = config.pricing.minPrice,
  } = options;
  
  // Base calculation
  const distanceCharge = distanceMiles * perMileRate;
  
  // Weight surcharge for loads over 500 lbs
  const overweightLbs = Math.max(0, weightLbs - 500);
  const weightCharge = overweightLbs * perPoundRate;
  
  // Base price
  let basePrice = baseFee + distanceCharge + weightCharge;
  
  // Fuel surcharge
  const fuelSurcharge = basePrice * (fuelSurchargePercent / 100);
  
  // Subtotal before platform fee
  const subtotal = basePrice + fuelSurcharge;
  
  // Platform fee
  const platformFee = subtotal * (platformFeePercent / 100);
  
  // Total price (what shipper pays)
  let totalPrice = subtotal + platformFee;
  
  // Enforce minimum price
  if (totalPrice < minPrice) {
    totalPrice = minPrice;
  }
  
  // Driver payout (total minus platform fee)
  const driverPayout = totalPrice - platformFee;
  
  return {
    basePrice: round2(basePrice),
    fuelSurcharge: round2(fuelSurcharge),
    platformFee: round2(platformFee),
    totalPrice: round2(totalPrice),
    driverPayout: round2(driverPayout),
    breakdown: {
      baseFee: round2(baseFee),
      distanceCharge: round2(distanceCharge),
      weightCharge: round2(weightCharge),
      distanceMiles: round2(distanceMiles),
      weightLbs,
    },
  };
};

/**
 * Estimate price before geocoding (rough estimate)
 */
const estimatePrice = (estimatedMiles, weightLbs) => {
  const result = calculatePrice(estimatedMiles, weightLbs);
  return {
    ...result,
    isEstimate: true,
    note: 'Final price calculated after address verification',
  };
};

// Round to 2 decimal places
const round2 = (num) => Math.round(num * 100) / 100;

module.exports = {
  calculatePrice,
  estimatePrice,
};
