// Generated by ScriptBuilder - 303 – Database Schema
// Feature: database | Role: schema

// =========================================================
// 004 – Database Schema
// Feature: database
// Role: schema
// Group: Database
// =========================================================
// FILE: src/db/migrate.js
// Run with: npm run db:migrate
// =========================================================
