// Generated by ScriptBuilder - 326 – Additional Schema (Documents, Disputes)
// Feature: core | Role: core

// =========================================================
// 326 – Additional Schema (Documents, Disputes)
// Feature: database
// Role: migrations
// Group: Backend API
// =========================================================
// FILE: src/db/migrations_v2.js
// =========================================================

const { pool } = require('./pool');







// === END REQUIRES ===

const runMigrationsV2 = async () => {
  try {
    console.log('[DB] Running v2 migrations...');
    // Migrations handled by PostgreSQL plugin
    console.log('[DB] V2 migrations complete!');
  } catch (error) {
    console.error('[DB] V2 migration error:', error);
    throw error;
  }
};

module.exports = { runMigrationsV2 };
