// Generated by ScriptBuilder - 301 – Environment & Constants
// Feature: core | Role: config

// =========================================================
// 002 – Environment & Constants
// Feature: core
// Role: config
// Group: Setup
// =========================================================
// FILE: src/config/index.js
// =========================================================

require('dotenv').config();

const config = {
  // Server
  port: process.env.PORT || 3000,
  nodeEnv: process.env.NODE_ENV || 'development',
  
  // Database
  database: {
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT) || 5432,
    name: process.env.DB_NAME || 'hotshot',
    user: process.env.DB_USER || 'postgres',
    password: process.env.DB_PASSWORD || '',
  },
  
  // Redis
  redis: {
    host: process.env.REDIS_HOST || 'localhost',
    port: parseInt(process.env.REDIS_PORT) || 6379,
  },
  
  // JWT
  jwt: {
    secret: process.env.JWT_SECRET || 'change-this-in-production',
    expiresIn: process.env.JWT_EXPIRES_IN || '7d',
  },
  
  // Stripe
  stripe: {
    secretKey: process.env.STRIPE_SECRET_KEY || '',
    webhookSecret: process.env.STRIPE_WEBHOOK_SECRET || '',
  },
  
  // Firebase (for push notifications)
  firebase: {
    projectId: process.env.FIREBASE_PROJECT_ID || '',
  },

  // AWS (for S3 document storage)
  aws: {
    region: process.env.AWS_REGION || 'us-east-1',
    accessKeyId: process.env.AWS_ACCESS_KEY_ID || '',
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || '',
    s3Bucket: process.env.AWS_S3_BUCKET || 'hotshot-documents',
  },

  // Checkr (background checks)
  checkr: {
    apiKey: process.env.CHECKR_API_KEY || '',
    sandbox: process.env.CHECKR_SANDBOX !== 'false',
  },
  
  // Pricing
  pricing: {
    baseFee: 25.00,           // Base fee per load
    perMileRate: 2.50,        // Rate per mile
    perPoundRate: 0.10,       // Rate per pound over 500lbs
    fuelSurchargePercent: 15, // Fuel surcharge percentage
    platformFeePercent: 10,   // Hotshot platform fee
    minPrice: 50.00,          // Minimum load price
  },
  
  // Matching
  matching: {
    radiusMiles: 25,          // Default driver search radius
    maxRadiusMiles: 100,      // Maximum search radius
  },
};

module.exports = config;
