// Generated by ScriptBuilder - 315 — Express App Setup
// Feature: core | Role: app

const express = require('express');
const cors = require('cors');
const helmet = require('helmet');

const config = require('./config');

// Import routes
const authRoutes = require('./routes/auth');
const usersRoutes = require('./routes/users');
const driverRoutes = require('./routes/drivers');
const loadRoutes = require('./routes/loads');
const paymentRoutes = require('./routes/payments');
const routePlannerRoutes = require('./routes/route-planner');
const ratingsRoutes = require('./routes/ratings');
const companyRoutes = require('./routes/company');
const announcementsRoutes = require('./routes/announcements');
const ratesRoutes = require('./routes/rates');
const matchingRoutes = require('./routes/matching');
const notificationsRoutes = require('./routes/notifications');
const dispatchRoutes = require('./routes/dispatch');
const brokerRoutes = require('./routes/broker');
const closeoutRoutes = require('./routes/closeouts');

// CREATE APP FIRST - before any app.use() calls
const app = express();

// ---------------------------------------------------------
// Middleware
// ---------------------------------------------------------

// Security headers
app.use(helmet());

// CORS
app.use(cors({
  origin: config.nodeEnv === 'production' 
    ? ['https://hotshot.app', 'https://api.hotshot.app']
    : '*',
  credentials: true,
}));

// Body parsing
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));

// Request logging (development)
if (config.nodeEnv === 'development') {
  app.use((req, res, next) => {
    console.log(`[${new Date().toISOString()}] ${req.method} ${req.path}`);
    next();
  });
}

// ---------------------------------------------------------
// Health Check
// ---------------------------------------------------------

app.get('/health', (req, res) => {
  res.json({ 
    status: 'ok', 
    timestamp: new Date().toISOString(),
    version: '1.0.0',
  });
});

// ---------------------------------------------------------
// API Routes
// ---------------------------------------------------------

app.use('/api/auth', authRoutes);
app.use('/api/users', usersRoutes);
app.use('/api/drivers', driverRoutes);
app.use('/api/loads', loadRoutes);
app.use('/api/payments', paymentRoutes);
app.use('/api/route-planner', routePlannerRoutes);
app.use('/api/ratings', ratingsRoutes);
app.use('/api/company', companyRoutes);
app.use('/api/announcements', announcementsRoutes);
app.use('/api/dispatchers', require('./routes/dispatchers'));
app.use('/api/invoices', require('./routes/invoices'));
app.use('/api/orgs', require('./routes/orgs'));
app.use('/api/offers', require('./routes/offers'));
app.use('/api/assignments', require('./routes/assignments'));
app.use('/api/dispatch', dispatchRoutes);
app.use('/api/rates', ratesRoutes);
app.use('/api/matching', matchingRoutes);
app.use('/api/notifications', notificationsRoutes);
app.use('/api/broker', brokerRoutes);
app.use('/api/closeouts', closeoutRoutes);
app.use('/api', require('./routes/activity'));

// Previously unmounted routes (identified in API audit)
app.use('/api/documents', require('./routes/documents'));
app.use('/api/verification', require('./routes/verification'));
app.use('/api/tracking', require('./routes/tracking'));
app.use('/api/disputes', require('./routes/disputes'));
app.use('/api/support', require('./routes/support'));
app.use('/api/admin', require('./routes/admin'));

// ---------------------------------------------------------
// Error Handling
// ---------------------------------------------------------

// 404 handler
app.use((req, res) => {
  res.status(404).json({ 
    error: 'Not found',
    path: req.path,
  });
});

// Global error handler
app.use((err, req, res, next) => {
  console.error('[Error]', err);
  
  // Don't leak error details in production
  const message = config.nodeEnv === 'production' 
    ? 'Internal server error' 
    : err.message;
  
  res.status(err.status || 500).json({ 
    error: message,
    ...(config.nodeEnv !== 'production' && { stack: err.stack }),
  });
});

module.exports = app;
